# Generated by Django 5.1.5 on 2025-05-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0002_remove_artist_avatar'),
        ('importer', '0001_initial'),
        ('songs', '0003_remove_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumlink',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='albums.album'),
        ),
        migrations.AddField(
            model_name='artistlink',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='songlink',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='songs.song'),
        ),
    ]
