# Generated by Django 5.1.5 on 2025-04-25 18:13

import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('released_at', models.SmallIntegerField(validators=[shared.validators.validate_year_range])),
                ('cover', models.ImageField(default='covers/default.jpg', upload_to='covers/')),
                ('added_at', models.DateField(auto_now_add=True)),
                ('artists', models.ManyToManyField(related_name='albums', to='artists.artist')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
