# Generated by Django 5.1.5 on 2025-05-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='lbz_url',
            field=models.URLField(default='hola.com'),
        ),
    ]
