# Generated by Django 5.1.5 on 2025-01-29 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('title',)},
        ),
    ]
