# Generated by Django 5.1.5 on 2025-05-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='released_at',
            field=models.DateField(),
        ),
    ]
