# Generated by Django 5.1.5 on 2025-05-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_lbz_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='lbz_url',
            field=models.URLField(),
        ),
    ]
