# Generated by Django 5.1.5 on 2025-05-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_squashed_0003_alter_album_released_at'),
        ('artists', '0001_squashed_0002_alter_artist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('artists', models.ManyToManyField(related_name='songs', to='artists.artist')),
                ('albums', models.ManyToManyField(related_name='songs', to='albums.album')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
