# Generated by Django 5.1.5 on 2025-02-26 23:05

import django.db.models.deletion
import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('released_at', models.SmallIntegerField(validators=[shared.validators.validate_year_range])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='albums.album')),
                ('artists', models.ManyToManyField(related_name='songs', to='artists.artist')),
                ('genre', models.ManyToManyField(related_name='songs', to='genres.genre')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
