# Generated by Django 5.1.5 on 2025-01-29 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('title',)},
        ),
    ]
