# Generated by Django 5.1.5 on 2025-01-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
