# Generated by Django 5.1.5 on 2025-05-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
    ]
