# Generated by Django 5.1.5 on 2025-01-30 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_genre_options_alter_song_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='added_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
