# Generated by Django 5.1.5 on 2025-05-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_released_at'),
        ('songs', '0004_alter_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(related_name='songs', to='albums.album'),
        ),
    ]
