# Generated by Django 5.1.5 on 2025-02-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_initial'),
        ('songs', '0003_delete_genre_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='songs.song'),
        ),
    ]
