# Generated by Django 5.1.5 on 2025-01-29 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ('title',)},
        ),
    ]
