# Generated by Django 5.1.5 on 2025-05-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='avatar',
        ),
    ]
