# Generated by Django 5.1.5 on 2025-02-05 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('users', '0002_profile_token_alter_profile_liked_albums_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
