# Generated by Django 5.1.5 on 2025-01-29 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_artist_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('name',)},
        ),
    ]
