# Generated by Django 5.1.5 on 2025-05-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_artist_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(default='/avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
