# Generated by Django 5.1.5 on 2025-02-05 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_profile'),
        ('users', '0002_profile_token_alter_profile_liked_albums_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profile', to='users.profile'),
        ),
    ]
