# Generated by Django 5.1.5 on 2025-02-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artist_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='profile',
        ),
    ]
