# Generated by Django 5.1.5 on 2025-02-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
