# Generated by Django 5.1.5 on 2025-02-02 01:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
        ('playlists', '0003_alter_playlist_songs'),
        ('songs', '0003_delete_genre_alter_song_genre'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_albums',
            field=models.ManyToManyField(blank=True, related_name='likes', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_artists',
            field=models.ManyToManyField(blank=True, related_name='likes', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_playlist',
            field=models.ManyToManyField(blank=True, related_name='likes', to='playlists.playlist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='likes', to='songs.song'),
        ),
    ]
